name: PyPI Release

# https://help.github.com/en/actions/reference/events-that-trigger-workflows
on: # Trigger the workflow on push to master branch with changes in __about__.py
  push:
    branches:
      - "master"
    paths:
      - "lightning_training_studio/__about__.py"

# based on https://github.com/pypa/gh-action-pypi-publish
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: >-
          python -m pip install --user --upgrade setuptools wheel

      - name: Install Lightning
        run: |
          python -m pip install -r requirements.txt --quiet
          python -m pip install . --quiet

      - name: Build
        run: >-
          python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.5
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
